### ISSUE TITLE
Add geocoded_location

### ISSUE THREAD

**Issue by home409ca** [pnbruckner/ha-google-maps#29] opened 2024-07-15 20:41 UTC
![image](https://github.com/user-attachments/assets/0e5b89b6-9aea-4f15-930c-ba80ad3ad602)
Add geocoding of location similarly to the mobile app data. In particular, the "locality" attribute

**Comment by pnbruckner** [comment] 2024-07-16 13:41
This is basically a duplicate of #24. If you don't agree, feel free to reopen and state why.

**Closed by pnbruckner** 2024-07-16 13:41 UTC
Labels: duplicate
