### ISSUE TITLE
Report address via separate attributes instead of all together as "address"

### ISSUE THREAD

**Issue by elbel86** [pnbruckner/ha-google-maps#24] opened 2024-03-17 19:28 UTC
I think this would be more useful in automations if it broke down the geocoded address into separate attributes like the HA companion app does.

Currently this integration reports a single "address" attribute with the house number, street name, city, zip, county all in one string.

Ideally, it could report each as a separate attribute like the HA companion app that provides the following attributes:
administrative_are, country, iso_country_code, locality, location, name, phone, postal_code, premises, sub_administrative_area, sub_locality, sub_thoroughfare, thoroughfare

Now, perhaps we don't need all of these, like phone or thoroughfare, I don't even know what some of them are for, but it would be convenient to have things like city and country in separate attributes for easy automation.

**Comment by pnbruckner** [comment] 2024-03-18 13:42
Yes, that might be useful. The problem is the Google server does not provide the individual pieces of the data separated out. It only provides it in the form you see, as a single string. This HA integration is providing the data in an attribute as an "FYI". I would have no way to know how it might be formatted in all cases, and hence, how to parse it into the individual pieces of data. E.g., how the address is reported in the US is probably completely different in different countries.

So, although it might be useful to do this, it's not clear how to do so reliably. In this case, it's probably better for the user, who has more knowledge of how the data is usually formatted in their use cases, to parse the data out via a template somewhere.

**Comment by pnbruckner** [comment] 2024-03-18 14:17
FWIW, this feature might be better implemented in my [Entity Time Zone](https://github.com/pnbruckner/ha-entity-tz) integration. It currently only displays a single string in its address sensor. But the individual pieces of data are provided by the source, which is geopy's nominatim module. Details of the individual pieces of data available are documented here: https://nominatim.org/release-docs/develop/api/Output/#addressdetails.

**Comment by elbel86** [comment] 2024-03-18 15:11
Understandable, I was trying to put together a template for it and thought it would be easier if it was like the companion app, but if that's the data Google provides, I see how that would be an issue.  Makes me wonder exactly how the HA app gets that info, they must use a different service for geolocation.

Anyway, I really appreciate the work you've done, this integration is so much easier to use than the official one, hopefully you can get this made the default in HA core. I know a lot of people struggle to set up the other one and yours is much easier.

**Comment by pnbruckner** [comment] 2024-03-18 16:03
Do you think you might be interested in using my Entity Time Zone integration if it had the feature to provide "broken down" address details? FWIW, it currently uses geopy's nominatim module (which gets its data from OpenStreetMap, which is free), but it can also use Google as a source (although that requires a paid API key.) I have found that Google does a better job of figuring out the address than nominatim/OSM, but then again, you get what you pay (or don't pay) for! 😆

**Comment by elbel86** [comment] 2024-03-18 16:54
So I could use this integration along with the Google maps one, to get a geocoded address of the maps entity (or any address I guess)?  I just skimmed over it a bit, it sounds like it would work

**Comment by pnbruckner** [comment] 2024-03-18 18:01
The Entity Time Zone integration takes as input any entity that has latitude & longitude attributes (so, yes, it could use a Google Maps device_tracker entity), and then does a reverse lookup to come up with an address (and associated data.) It can also do a time zone lookup (using a different package.)

When you say, "get a geocoded address", is that what you mean? Geocoding, as far as I know, does the opposite. I.e., it takes an address and finds its location (latitude & longitude. FWIW, nominatim can do both, but I've only used the reverse method, not the geocode method.)

**Comment by elbel86** [comment] 2024-03-18 18:38
Yeah, that's exactly what I mean.  Turn the coordinates from the maps entity into an address.  I'll have to give the other integration a try when I have some time to mess around with it.

**Comment by pnbruckner** [comment] 2024-05-28 15:52
Closing since this integration can't really implement such a feature. See https://github.com/pnbruckner/ha-entity-tz/issues/10 instead.

**Closed by pnbruckner** 2024-05-28 15:52 UTC
Labels: enhancement
