### ISSUE TITLE
ERROR: Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

### ISSUE THREAD

**Issue by yakeer** [pnbruckner/ha-google-maps#28] opened 2024-06-27 06:04 UTC
Hey,
Thanks for your work.

I've installed the plugin, did the "cookie" thing just as mentioned and everything works as expected.
After few minutes I get the "Reconfigure error", and when I click it that's the error I get.

In order to sort it out for a few minutes, I have to export a new cookie, update hidden cookie file in HA, and restart HA.

It does succeed to communicate, because I can see new entities, it seems that the cookie gets invalidated really often.
I did not sign out the alt account or anything similar.

Versions:
Core 2024.6.4
Supervisor 2024.06.2
Operating System 12.4
Frontend 20240610.1
Google Maps Plugin: 1.3.2

Any idea what am I doing wrong here?

**Comment by pnbruckner** [comment] 2024-06-27 13:07
Honestly, I don't have any idea. If you followed the instructions to obtain the cookies file, and did NOT sign out of the browser you used to get that cookie, just closed it, then I don't know why it would become invalid so quickly. Also, I have no idea why some people get this error 500. I can't reproduce either scenario myself.

**Comment by pnbruckner** [comment] 2024-06-27 13:27
Besides the error 500 you mentioned, which I'm guessing you're seeing in the UI when you try to start the config flow, do you see any errors in the system log?

**Comment by jezzaaa** [comment] 2024-07-08 08:20
I just got this error today, after a couple of weeks of installing the integration and having it work perfectly all that time. I had a "Repair" show up today, and when I click on the repair, I get this error. Also, red "Reconfigure" button on the integration, clicking on it gives me the same result.

**Comment by jezzaaa** [comment] 2024-07-08 08:28
A couple of days ago:

Source: custom_components/google_maps/device_tracker.py:132
integration: Google Maps (documentation, issues)
First occurred: 5 July 2024 at 21:15:50 (1 occurrences)
Last logged: 5 July 2024 at 21:15:50

Received response code 500 with context )]}' [["er",null,null,null,null,500,null,null,null,13],["di",3455]]

**Comment by jezzaaa** [comment] 2024-07-08 08:30
And today:.

Source: helpers/update_coordinator.py:365
integration: Google Maps (documentation, issues)
First occurred: 7 July 2024 at 17:16:42 (1 occurrences)
Last logged: 7 July 2024 at 17:16:42

Authentication failed while fetching redacted@redacted .org data: InvalidCookies: Invalid session indicated

**Comment by pnbruckner** [comment] 2024-07-08 13:19
@jezzaaa, it looks like you're still using the "legacy" tracker configuration; i.e., you have something like the following in your YAML configuration:
```yaml
device_tracker:
  - platform: google_maps
```
Please convert to UI-based configuration. See the [docs](https://github.com/pnbruckner/ha-google-maps). Once you've done that, if you're still having problems, let me know.

**Comment by jezzaaa** [comment] 2024-07-11 03:13
Yeah, you picked it. Thanks

**Comment by pnbruckner** [comment] 2024-07-16 13:23
@yakeer, are you still having problems with this?

**Comment by yakeer** [comment] 2024-07-16 13:30
Actually I had to remove it, because it didn't work at all.
Did you update anything so I could check if it's now working?

**Comment by pnbruckner** [comment] 2024-07-16 13:47
I did not update anything. I've been waiting for the additional information from you I asked for above. I cannot reproduce the problem, so I need more details before I can attempt to resolve the problem.

**Comment by htomasz** [comment] 2024-07-20 14:36
I just install because legacy is not working for me from few weeks. And i  got the same error "Nie udało się wczytać interfejsu konfiguracji: 500 Internal Server Error Server got itself in trouble"

**Comment by LazzaAU** [comment] 2024-08-03 06:48
I get the same issue , so if theres any further info you need then i'm happy to provide it if the original poster has gone quiet :)

for reference in my log file i do get this 

```
Logger: aiohttp.server
Source: /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:421
First occurred: 4:22:54 PM (3 occurrences)
Last logged: 4:23:38 PM

Error handling request
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
    resp = await request_handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
    resp = await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 92, in security_filter_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 83, in forwarded_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 26, in request_context_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 85, in ban_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 242, in auth_middleware
    return await handler(request)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 32, in headers_middleware
    response = await handler(request)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/http.py", line 73, in handle
    result = await handler(request, **request.match_info)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 81, in with_admin
    return await func(self, request, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 215, in get
    return await super().get(request, flow_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 108, in get
    result = await self._flow_mgr.async_configure(flow_id)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 368, in async_configure
    result = await self._async_configure(flow_id, user_input)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 415, in _async_configure
    result = await self._async_handle_step(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 518, in _async_handle_step
    result: _FlowResultT = await getattr(flow, method)(user_input)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/google_maps/config_flow.py", line 163, in async_step_old_cookies_invalid
    assert cf_path
           ^^^^^^^
AssertionError
```

UPDATE: so i tried 3 times going through the motions of setting up this integration and each time it worked without fail until i rebooted and it then told me the 500 internal error issue. I'm not saying the following was a fix but.... i did jump back into my main config directory and deleted the original legacy cookie file that i had since day dot, then i rebooted and re set up this integration and the internal error went away. Coincedence ? no idea, but just as a point to think about if you get this error perhaps try deleting existing cookie files you may of previously had whether its relevant to this error or not, for now it came right for me *shrug* or maybe it was just 4 h time lucky :)

**Comment by LazzaAU** [comment] 2024-08-04 05:55
actually forget my last comment, the issue re appeared an hour later despite the cookies being valid until 2025, still investi
gating :)

**Comment by pnbruckner** [comment] 2024-08-09 19:59
@LazzaAU, thanks for the detailed log message. That finally gives me something to go on. I'm not sure how this exception is happening, but at least I have enough info now to try and reproduce it, and hopefully fix it.

**Closed** 2024-08-12 14:42 UTC

**Comment by pnbruckner** [comment] 2024-08-12 14:55
@yakeer, @jezzaaa, @htomasz, @LazzaAU, I believe I have fixed the issue with the config flow that handles the RECONFIGURE option presented when a cookies file expires or otherwise is determined to be invalid. I will release that fix soon. This issue has, therefore, been closed because that is the problem originally described.

Feel free to open a separate issue regarding the cookies file "expiring" prematurely, or more to the point, being considered invalid by the Google server. However, be aware, that ground has been covered extensively, and as far as I know, I've done as much as I can to address that problem by writing extensive instructions for how to grab a cookies file.

**Comment by jezzaaa** [comment] 2024-08-28 07:23
@pnbruckner, I haven't had the problem since your update. The GUI workflow worked perfectly. Thanks!
